export const jobsArray=[
    'React Developer',
    'Angular Developer',
    'Node Developer',
    'Python Developer',
    'Java Developer',
    'C++ Developer',
    'C# Developer',
    'Ruby Developer',
    'PHP Developer',
    'Javascript Developer',
    'Golang Developer',
    'C Developer',
    'Accountant',
    'Business Analyst',
    'Software Engineer',
    'Software Developer',
    'Project Manager',
    'Sales Manager',
    'Marketing Manager',
    'HR Manager',
    'UI/UX Designer',
    'UX Designer',
    'Product Designer',
    'Web Designer',
    'UX/UI Designer',
    'UI Designer',
    'Graphic Designer',
    'Frontend Developer',
    'Backend Developer',
    'Full Stack Developer',
    'DevOps Engineer',
    'DevOps Engineer',
    'Data Scientist',
    'Data Engineer',
]
export const skillsArray=[
    'clean code',
    'code quality',
    'communication',
    'teamwork',
    'problem solving',
    'critical thinking',
    'time management',
    'microsoft 365',
    'google workspace',
    'google sheets',
    'google drive',
    'google slides',
    'google forms',
    'google docs',
    'google sheets',
    'html',
    'css',
    'javascript',
    'typescript',
    'react',
    'node',
    'python',
    'java',
    'c++',
    'c#',
    'ruby',
    'php',
    'sql',
    'mongodb',
    'mysql',
    'git',
    'github',
    'docker',
    'kubernetes',
    'aws',
    'azure',
    'gcp',
    'c',
]