export const jobsArray=[
    'React Developer',
    'Angular Developer',
    'Node Developer',
    'Python Developer',
    'Java Developer',
    'C++ Developer',
    'C# Developer',
    'Ruby Developer',
    'PHP Developer',
    'Javascript Developer',
    'Golang Developer',
    'C Developer',
    'Accountant',
    'Business Analyst',
    'Software Engineer',
    'Software Developer',
    'Project Manager',
    'Sales Manager',
    'Marketing Manager',
    'HR Manager',
    'UI/UX Designer',
    'UX Designer',
    'Product Designer',
    'Web Designer',
    'UX/UI Designer',
    'UI Designer',
    'Graphic Designer',
    'Frontend Developer',
    'Backend Developer',
    'Full Stack Developer',
    'DevOps Engineer',
    'Data Scientist',
    'Data Engineer',
]
export const skillsArray=[
    'clean code',
    'code quality',
    'communication',
    'teamwork',
    'problem solving',
    'critical thinking',
    'time management',
    'microsoft 365',
    'google workspace',
    'google sheets',
    'google drive',
    'google slides',
    'google forms',
    'google docs',
    'google sheets',
    'html',
    'css',
    'javascript',
    'typescript',
    'react',
    'node',
    'python',
    'java',
    'c++',
    'c#',
    'ruby',
    'php',
    'sql',
    'mongodb',
    'mysql',
    'git',
    'github',
    'docker',
    'kubernetes',
    'aws',
    'azure',
    'gcp',
    'c',
]
export const jobs = [
    { id: 1, name: 'React Developer' },
    { id: 2, name: 'Angular Developer' },
    { id: 3, name: 'Full Stack Developer' },
    { id: 4, name: 'Frontend Developer' },
    { id: 5, name: 'Backend Developer' },
    { id: 6, name: 'Java Developer' },
    { id: 7, name: 'Python Developer' },
    { id: 8, name: 'Software Engineer' },
    { id: 9, name: 'Data Scientist' },
    { id: 10, name: 'Machine Learning Engineer' },
    { id: 11, name: 'DevOps Engineer' },
    { id: 12, name: 'Product Manager' },
    { id: 13, name: 'Project Manager' },
    { id: 14, name: 'UX/UI Designer' },
    { id: 15, name: 'Quality Assurance Engineer' },
    { id: 16, name: 'Cloud Engineer' },
    { id: 17, name: 'Cybersecurity Analyst' },
    { id: 18, name: 'Database Administrator' },
    { id: 19, name: 'Systems Analyst' },
    { id: 20, name: 'IT Support Specialist' },
    { id: 21, name: 'Network Engineer' },
    { id: 22, name: 'Information Security Manager' },
    { id: 23, name: 'Scrum Master' },
    { id: 24, name: 'Web Developer' },
    { id: 25, name: 'Mobile App Developer' },
    { id: 26, name: 'Digital Marketing Specialist' },
    { id: 27, name: 'SEO Specialist' },
    { id: 28, name: 'Content Writer' },
    { id: 29, name: 'Graphic Designer' },
    { id: 30, name: 'Social Media Manager' },
    { id: 31, name: 'Financial Analyst' },
    { id: 32, name: 'Accountant' },
    { id: 33, name: 'Human Resources Manager' },
    { id: 34, name: 'Operations Manager' },
    { id: 35, name: 'Business Analyst' },
    { id: 36, name: 'Sales Manager' },
    { id: 37, name: 'Customer Service Manager' },
    { id: 38, name: 'Public Relations Specialist' },
    { id: 39, name: 'Executive Assistant' },
    { id: 40, name: 'Market Research Analyst' },
    { id: 41, name: 'Data Analyst' },
    { id: 42, name: 'Clinical Research Coordinator' },
    { id: 43, name: 'Healthcare Administrator' },
    { id: 44, name: 'Medical Billing Specialist' },
    { id: 45, name: 'Sales Representative' },
    { id: 46, name: 'Legal Assistant' },
    { id: 47, name: 'Paralegal' },
    { id: 48, name: 'Insurance Agent' },
    { id: 49, name: 'Loan Officer' },
    { id: 50, name: 'Financial Planner' },
    { id: 51, name: 'Investment Banker' },
    { id: 52, name: 'Bank Teller' },
    { id: 53, name: 'Economist' },
    { id: 54, name: 'Supply Chain Manager' },
    { id: 55, name: 'Purchasing Agent' },
    { id: 56, name: 'Logistics Coordinator' },
    { id: 57, name: 'Operations Research Analyst' },
    { id: 58, name: 'Construction Manager' },
    { id: 59, name: 'Real Estate Agent' },
    { id: 60, name: 'Architect' },
    { id: 61, name: 'Mechanical Engineer' },
    { id: 62, name: 'Electrical Engineer' },
    { id: 63, name: 'Civil Engineer' },
    { id: 64, name: 'Chemical Engineer' },
    { id: 65, name: 'Biomedical Engineer' },
    { id: 66, name: 'Environmental Engineer' },
    { id: 67, name: 'Geologist' },
    { id: 68, name: 'Chemist' },
    { id: 69, name: 'Physicist' },
    { id: 70, name: 'Biologist' },
    { id: 71, name: 'Pharmacist' },
    { id: 72, name: 'Nurse Practitioner' },
    { id: 73, name: 'Clinical Psychologist' },
    { id: 74, name: 'Radiologic Technologist' },
    { id: 75, name: 'Occupational Therapist' },
    { id: 76, name: 'Speech-Language Pathologist' },
    { id: 77, name: 'Physical Therapist' },
    { id: 78, name: 'Veterinarian' },
    { id: 79, name: 'Dentist' },
    { id: 80, name: 'Surgeon' },
    { id: 81, name: 'Physician' },
    { id: 82, name: 'Pilot' },
    { id: 83, name: 'Air Traffic Controller' },
    { id: 84, name: 'Software Tester' },
    { id: 85, name: 'Electronics Technician' },
    { id: 86, name: 'Technical Writer' },
    { id: 87, name: 'Content Strategist' },
    { id: 88, name: 'Event Planner' },
    { id: 89, name: 'Interior Designer' },
    { id: 90, name: 'Fashion Designer' },
    { id: 91, name: 'Brand Manager' },
    { id: 92, name: 'Copywriter' },
    { id: 93, name: 'Photographer' },
    { id: 94, name: 'Video Editor' },
    { id: 95, name: 'Animator' },
    { id: 96, name: 'Game Designer' },
    { id: 97, name: 'Art Director' },
    { id: 98, name: 'Editor' },
    { id: 99, name: 'Translator' },
    { id: 100, name: 'Interpreter' }
];
